# docker-compose version
version: '3.8'

# Containers
services:
  # Node.js
  web_server:
  # Define the container's name, the dockerfile we want to build it from and the main directory 
    build:
      context: ./nodejs_server
      dockerfile: Dockerfile
    container_name: wolt_web_server
    # Bind the server to port 3000
    ports:
      - "3000:3000"
    # Environment Variables  
    environment:
      - NODE_ENV=development
      - PORT=3000
      # The JWT secret key is added as an environment variable
      - JWT_SECRET
      # Define inner comunication lane between the containers , the cpp server is now: cpp_backend
      - CPP_BACKEND_URL=http://cpp_backend:8080 
    # connect the container into a the same network as the other container  
    networks:
      - wolt_network
    # dont run this dockerfile before cpp_backend is running  
    depends_on:
      cpp_backend:
        condition: service_started

  # Cpp server
  cpp_backend:
  # Define the container's name, the dockerfile we want to build it from and the main directory
    build:
      context: ./cpp_server
      dockerfile: Dockerfile
    container_name: wolt_cpp_backend
    # Bind the server to port 8080
    ports:
      - "8080:8080" 
    # connect the container into a the same network as the other container    
    networks:
      - wolt_network
    # Run the container and wait for cli   
    stdin_open: true 
    tty: true
    # Automatically build and run the C++ server
    command: bash -c "mkdir -p build && cd build && cmake .. && make && ./wolt_app 8080"

# Create the private connected-network between the containers
networks:
  wolt_network:
    driver: bridge